server:
  port: 8081

spring:
  application:
    name: user-couple-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: stockroom_user
    password: stockroom_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # OAuth2 설정 제거 - JWT 인증만 사용

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-make-it-long-enough}
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.couple: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    root: INFO

# Eureka 설정 제거 - 직접 주소 사용

management:
  endpoints:
    web:
      exposure:
        include: health,info 