server:
  port: 8086

spring:
  application:
    name: question-answer-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/question_answer_db
    username: stockroom_user
    password: stockroom_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: question_answer_db
      authentication-database: admin
      username: mongoadmin
      password: secretpass
  
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    com.couple.question_answer: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 