apiVersion: apps/v1
kind: Deployment
metadata:
  name: couple-chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: couple-chat-service
  template:
    metadata:
      labels:
        app: couple-chat-service
    spec:
      containers:
        - name: couple-chat-service
          image: 624227064848.dkr.ecr.ap-northeast-2.amazonaws.com/couple-chat-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: couple-chat-service
spec:
  selector:
    app: couple-chat-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
