apiVersion: apps/v1
kind: Deployment
metadata:
  name: livechat-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: livechat-django
  template:
    metadata:
      labels:
        app: livechat-django
    spec:
      containers:
        - name: livechat-django
          image: 624227064848.dkr.ecr.ap-northeast-2.amazonaws.com/livechat-django:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: livechat-django
spec:
  selector:
    app: livechat-django
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
