apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-answer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question-answer-service
  template:
    metadata:
      labels:
        app: question-answer-service
    spec:
      containers:
        - name: question-answer-service
          image: 624227064848.dkr.ecr.ap-northeast-2.amazonaws.com/question-answer-service:latest
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: question-answer-service
spec:
  selector:
    app: question-answer-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
