apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-meeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schedule-meeting-service
  template:
    metadata:
      labels:
        app: schedule-meeting-service
    spec:
      containers:
        - name: schedule-meeting-service
          image: 624227064848.dkr.ecr.ap-northeast-2.amazonaws.com/schedule-meeting-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-meeting-service
spec:
  selector:
    app: schedule-meeting-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
