server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: django-websocket
          uri: ws://localhost:8000
          predicates:
            - Path=/ws/**
          filters:
            - RewritePath=/ws/(?<segment>.*), /ws/
            - name: WebSocketAuthFilter
  security:
    # OAuth2 설정 제거 - Gateway에서는 JWT 인증만 사용

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-make-it-long-enough}
  expiration: 86400000 # 24시간

# Eureka 설정 제거 - 직접 주소 사용

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    com.couple.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG 