server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: django-websocket
          uri: ws://localhost:8000
          predicates:
            - Path=/ws/**
          filters:
            - RewritePath=/ws/(?<segment>.*), /ws/
            - name: WebSocketAuthFilter
        - id: user-couple-service
          uri: http://user-couple-service:8081
          predicates:
            - Path=/api/users/**, /api/couples/**
          filters:
            - name: JwtAuthenticationFilter
        - id: schedule-meeting-service
          uri: http://schedule-meeting-service:8082
          predicates:
            - Path=/api/schedules/**, /api/meetings/**
          filters:
            - name: JwtAuthenticationFilter
        - id: question-answer-service
          uri: http://question-answer-service:8086
          predicates:
            - Path=/api/questions/**, /api/user-answers/**, /api/user-tag-profiles/**, /api/tags/**, /api/user-vectors/**
          filters:
            - name: JwtAuthenticationFilter
        - id: mission-store-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/missions/**, /api/shop/**
          filters:
            - name: JwtAuthenticationFilter
  security:
    # OAuth2 설정 제거 - Gateway에서는 JWT 인증만 사용

jwt:
  secret: ${JWT_SECRET:mySuperStrongSecretKeyThatIsLongEnough}
  expiration: 86400000 # 24시간

# Eureka 설정 제거 - 직접 주소 사용

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    com.couple.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG