server:
  port: 8088

spring:
  application:
    name: mission-store-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mission_store_db
    username: stockroom_user
    password: stockroom_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    com.couple.mission_store: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 