server:
  port: 8082

spring:
  application:
    name: schedule-meeting-service
  profiles:
    active: local

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.couple.schedule_meeting: DEBUG
    org.springframework.security: DEBUG
