server:
  port: 8082

spring:
  application:
    name: schedule-meeting-service
  datasource:
    url: jdbc:postgresql://localhost:5432/couple_schedule_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: local

# 외부 서비스 URL 설정
question-answer-service:
  url: http://localhost:8086

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.couple.schedule_meeting: DEBUG
    org.springframework.security: DEBUG

# Kakao API 설정
kakao:
  api:
    key: ${KAKAO_API_KEY:your-kakao-api-key-here}
